/**
 * Scan Profile definitions — pre-configured settings bundles.
 *
 * Each profile defines optimal settings for a different scanning scenario.
 * The "optimal" profile is the default and recommended for most users.
 */
export interface ScanProfile {
  id: string
  name: string
  description: string
  icon: string  // emoji
  settings: Record<string, unknown>
}

export const SCAN_PROFILES: ScanProfile[] = [
  {
    id: 'optimal',
    name: 'Optimal',
    description: 'Best settings for most scans. Full discovery, all modules, standard timing.',
    icon: '🎯',
    settings: {
      scanProfile: 'optimal',
      scanModules: ['domain_discovery', 'port_scan', 'http_probe', 'resource_enum', 'vuln_scan'],
      nucleiSeverity: ['critical', 'high', 'medium'],
      nucleiTemplates: [],
      nucleiTags: [],
      nucleiMaxConcurrent: 5,
      stealthMode: false,
      dnsEnabled: true,
      whoisEnabled: true,
      shodanEnabled: true,
      httpxEnabled: true,
      naabuEnabled: true,
      masscanEnabled: false,
      nmapEnabled: true,
      naabuRate: 1000,
      nmapTiming: 4,
      httpxThreads: 50,
      katanaEnabled: true,
      katanaDepth: 3,
      gauEnabled: true,
      ffufEnabled: true,
      arjunEnabled: true,
      jsluiceEnabled: false,
      kiterunnerEnabled: false,
      graphqlScanEnabled: false,
      nucleiEnabled: true,
      cveIntelEnabled: true,
      mitreEnabled: true,
      osintEnrichmentEnabled: true,
      uncoverEnabled: true,
      subdomainTakeoverEnabled: false,
      aiInPipeline: false,
      maxIterations: 100,
      useTorForRecon: false,
      activatePostExplPhase: true,
      postExplPhaseType: 'statefull',
    },
  },
  {
    id: 'stealth',
    name: 'Stealth',
    description: 'Slow and quiet. Rate-limited, no aggressive scans, Tor routing.',
    icon: '🥷',
    settings: {
      scanProfile: 'stealth',
      scanModules: ['domain_discovery', 'port_scan', 'http_probe', 'vuln_scan'],
      nucleiSeverity: ['critical', 'high'],
      stealthMode: true,
      dnsEnabled: true,
      whoisEnabled: false,
      shodanEnabled: false,
      httpxEnabled: true,
      naabuEnabled: true,
      masscanEnabled: false,
      nmapEnabled: true,
      naabuRate: 100,
      nmapTiming: 1,
      httpxThreads: 5,
      katanaEnabled: false,
      gauEnabled: false,
      ffufEnabled: false,
      arjunEnabled: false,
      jsluiceEnabled: false,
      kiterunnerEnabled: false,
      graphqlScanEnabled: false,
      nucleiEnabled: true,
      nucleiMaxConcurrent: 1,
      cveIntelEnabled: false,
      mitreEnabled: false,
      osintEnrichmentEnabled: false,
      uncoverEnabled: false,
      subdomainTakeoverEnabled: false,
      aiInPipeline: false,
      maxIterations: 50,
      useTorForRecon: true,
      activatePostExplPhase: false,
    },
  },
  {
    id: 'aggressive',
    name: 'Aggressive',
    description: 'Maximum coverage. All modules, high rates, AI pipeline enabled.',
    icon: '⚡',
    settings: {
      scanProfile: 'aggressive',
      scanModules: ['domain_discovery', 'port_scan', 'http_probe', 'resource_enum', 'vuln_scan'],
      nucleiSeverity: ['critical', 'high', 'medium', 'low'],
      nucleiTags: ['cve', 'rce', 'sqli', 'xss', 'lfi', 'ssrf'],
      nucleiMaxConcurrent: 20,
      stealthMode: false,
      dnsEnabled: true,
      whoisEnabled: true,
      shodanEnabled: true,
      httpxEnabled: true,
      naabuEnabled: true,
      masscanEnabled: true,
      nmapEnabled: true,
      naabuRate: 3000,
      nmapTiming: 5,
      httpxThreads: 100,
      katanaEnabled: true,
      katanaDepth: 5,
      gauEnabled: true,
      ffufEnabled: true,
      arjunEnabled: true,
      jsluiceEnabled: true,
      kiterunnerEnabled: true,
      graphqlScanEnabled: true,
      nucleiEnabled: true,
      cveIntelEnabled: true,
      mitreEnabled: true,
      osintEnrichmentEnabled: true,
      uncoverEnabled: true,
      subdomainTakeoverEnabled: true,
      aiInPipeline: true,
      maxIterations: 200,
      useTorForRecon: false,
      activatePostExplPhase: true,
      postExplPhaseType: 'statefull',
    },
  },
  {
    id: 'quick',
    name: 'Quick Scan',
    description: 'Fast port scan + vuln check. Minimal surface, no OSINT.',
    icon: '🏃',
    settings: {
      scanProfile: 'quick',
      scanModules: ['port_scan', 'http_probe', 'vuln_scan'],
      nucleiSeverity: ['critical', 'high'],
      nucleiMaxConcurrent: 10,
      stealthMode: false,
      dnsEnabled: false,
      whoisEnabled: false,
      shodanEnabled: false,
      httpxEnabled: true,
      naabuEnabled: true,
      masscanEnabled: true,
      nmapEnabled: false,
      naabuRate: 2000,
      httpxThreads: 50,
      katanaEnabled: false,
      gauEnabled: false,
      ffufEnabled: false,
      arjunEnabled: false,
      jsluiceEnabled: false,
      kiterunnerEnabled: false,
      graphqlScanEnabled: false,
      nucleiEnabled: true,
      cveIntelEnabled: false,
      mitreEnabled: false,
      osintEnrichmentEnabled: false,
      uncoverEnabled: false,
      subdomainTakeoverEnabled: false,
      aiInPipeline: false,
      maxIterations: 50,
      useTorForRecon: false,
      activatePostExplPhase: false,
    },
  },
]

export function getProfileById(id: string): ScanProfile | undefined {
  return SCAN_PROFILES.find(p => p.id === id)
}

export const DEFAULT_PROFILE = 'optimal'
